// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8K6wnxJIR7pWNpUaaojzrtrF2amxDDY0',
    appId: '1:529052640371:web:cfc08d210622a88999b606',
    messagingSenderId: '529052640371',
    projectId: 'sikad-uir',
    authDomain: 'sikad-uir.firebaseapp.com',
    storageBucket: 'sikad-uir.firebasestorage.app',
    measurementId: 'G-MY4361NTFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBybnAX_nwJBVehLkueSLesZzIDs46wuxg',
    appId: '1:529052640371:android:82b4e35edcacfeda99b606',
    messagingSenderId: '529052640371',
    projectId: 'sikad-uir',
    storageBucket: 'sikad-uir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcYf2uLTtLZbLtS-DOKWn6ujXxYVYGiYo',
    appId: '1:529052640371:ios:5bfc858dcd85e18199b606',
    messagingSenderId: '529052640371',
    projectId: 'sikad-uir',
    storageBucket: 'sikad-uir.firebasestorage.app',
    iosBundleId: 'com.example.sikad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcYf2uLTtLZbLtS-DOKWn6ujXxYVYGiYo',
    appId: '1:529052640371:ios:5bfc858dcd85e18199b606',
    messagingSenderId: '529052640371',
    projectId: 'sikad-uir',
    storageBucket: 'sikad-uir.firebasestorage.app',
    iosBundleId: 'com.example.sikad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8K6wnxJIR7pWNpUaaojzrtrF2amxDDY0',
    appId: '1:529052640371:web:e76daf605d1d1b7e99b606',
    messagingSenderId: '529052640371',
    projectId: 'sikad-uir',
    authDomain: 'sikad-uir.firebaseapp.com',
    storageBucket: 'sikad-uir.firebasestorage.app',
    measurementId: 'G-VLE6JVDVZ3',
  );
}
